export const EXIF_CN: Record<string, { name: string; unit?: string }> = {
  Make: { name: '相机制造商' },
  Model: { name: '相机型号' },
  Orientation: { name: '图像方向' },
  XResolution: { name: '水平分辨率', unit: 'DPI' },
  YResolution: { name: '垂直分辨率', unit: 'DPI' },
  ResolutionUnit: { name: '分辨率单位' },
  Software: { name: '处理软件' },
  DateTime: { name: '修改时间' },
  YCbCrPositioning: { name: 'YCbCr 色彩定位' },
  ExposureTime: { name: '快门速度', unit: 's' },
  FNumber: { name: '光圈值' },
  ExposureProgram: { name: '曝光程序' },
  ISOSpeedRatings: { name: 'ISO 感光度' },
  ISO: { name: 'ISO 感光度' },
  DateTimeOriginal: { name: '拍摄时间' },
  DateTimeDigitized: { name: '数字化时间' },
  ShutterSpeedValue: { name: '快门速度 (APEX)' },
  ApertureValue: { name: '光圈值 (APEX)' },
  ExposureBiasValue: { name: '曝光补偿', unit: 'EV' },
  MaxApertureValue: { name: '最大光圈' },
  MeteringMode: { name: '测光模式' },
  Flash: { name: '闪光灯' },
  FocalLength: { name: '焦距', unit: 'mm' },
  ColorSpace: { name: '色彩空间' },
  PixelXDimension: { name: '图像宽度', unit: 'px' },
  PixelYDimension: { name: '图像高度', unit: 'px' },
  FocalLengthIn35mmFilm: { name: '等效焦距', unit: 'mm' },
  WhiteBalance: { name: '白平衡' },
  ExposureMode: { name: '曝光模式' },
  SceneCaptureType: { name: '场景类型' },
  GPSLatitude: { name: 'GPS 纬度' },
  GPSLongitude: { name: 'GPS 经度' },
  GPSAltitude: { name: 'GPS 海拔', unit: 'm' },
  GPSDateStamp: { name: 'GPS 日期' },
  GPSTimeStamp: { name: 'GPS 时间' },
  GPSImgDirection: { name: 'GPS 拍摄方向', unit: '°' },
  ImageDescription: { name: '图像描述' },
  Artist: { name: '作者' },
  Copyright: { name: '版权' },
  UserComment: { name: '用户备注' },
  LensModel: { name: '镜头型号' },
  LensMake: { name: '镜头制造商' },
  LensInfo: { name: '镜头信息' },
  BitsPerSample: { name: '每样本位数' },
  Compression: { name: '压缩方式' },
  PhotometricInterpretation: { name: '光度测量' },
  SamplesPerPixel: { name: '每像素样本数' },
  SubjectDistanceRange: { name: '拍摄距离' },
  SceneType: { name: '场景类型标识' },
  CustomRendered: { name: '自定义渲染' },
  DigitalZoomRatio: { name: '数字变焦比' },
  GainControl: { name: '增益控制' },
  Contrast: { name: '对比度' },
  Saturation: { name: '饱和度' },
  Sharpness: { name: '锐度' },
  SubjectArea: { name: '主体区域' },
  SensingMethod: { name: '感光元件类型' },
  FileSource: { name: '文件来源' },
  CFAPattern: { name: 'CFA 图案' },
  FlashEnergy: { name: '闪光强度' },
  SpectralSensitivity: { name: '光谱灵敏度' },
  OECF: { name: '光电转换函数' },
  BodySerialNumber: { name: '机身序列号', },
  CameraOwnerName: { name: '相机拥有者' },
  ThumbnailOffset: { name: '缩略图偏移' },
  ThumbnailLength: { name: '缩略图大小', unit: 'bytes' },
  InteropIndex: { name: '互操作性索引' },
  InteropVersion: { name: '互操作性版本' },
  RelatedImageWidth: { name: '关联图像宽度' },
  RelatedImageHeight: { name: '关联图像高度' },
  ExifVersion: { name: 'Exif 版本' },
  FlashPixVersion: { name: 'FlashPix 版本' },
  ComponentsConfiguration: { name: '组件配置' },
  CompressedBitsPerPixel: { name: '压缩比', unit: 'bits/px' },
  SubSecTime: { name: '时间精度（修改）' },
  SubSecTimeOriginal: { name: '时间精度（拍摄）' },
  SubSecTimeDigitized: { name: '时间精度（数字化）' },
}
